### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by yokee06** [IAmBlackHacker/Facebook-BruteForce#31]

**Comment by BFGBBRSDTNTR** [comment]
I Want to learn hacking for its prepparation i known all the attack and
its details but i don't know how to do pratical first i intall kali
linex in virtual box i faces a lot of pproblem and after this i install
kali as a hot operating system so i request you to help me in this cases
because when i open terminal and search for comman showing invalid

**Comment by slamichhnetune** [comment]
Can You describe your issue clearly and can you _mention_ the **Error** you are facing

> I Want to learn hacking for its prepparation i known all the attack and its details but i don't know how to do pratical first i intall kali linex in virtual box i faces a lot of pproblem and after this i install kali as a hot operating system so i request you to help me in this cases because when i open terminal and search for comman showing invalid
> […](#)

**Comment by baman9600** [comment]
Muja facebook hacking sika do

**Comment by slamichhnetune** [comment]
What??

**Comment by baman9600** [comment]
Facebook  k comments  dedo
